"""add_email_password_authentication

Revision ID: 95c71ed624f4
Revises:
Create Date: 2026-01-16 00:41:45.121091

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '95c71ed624f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'REJECTED', 'DELETED', name='driverstatus'), nullable=False),
    sa.Column('availability', sa.Enum('ONLINE', 'OFFLINE', 'ON_RIDE', name='driveravailability'), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('otp_secret', sa.String(length=255), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.String(length=10), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expiry', sa.DateTime(), nullable=True),
    sa.Column('license_document_url', sa.String(length=500), nullable=True),
    sa.Column('vehicle_registration_url', sa.String(length=500), nullable=True),
    sa.Column('insurance_document_url', sa.String(length=500), nullable=True),
    sa.Column('background_check_status', sa.String(length=50), nullable=False),
    sa.Column('vehicle_make', sa.String(length=100), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('vehicle_year', sa.String(length=4), nullable=True),
    sa.Column('vehicle_color', sa.String(length=50), nullable=True),
    sa.Column('vehicle_plate_number', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.Enum('SEDAN', 'SUV', 'MINI_VAN', 'LUXURY', name='vehicletype'), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_rides', sa.String(length=10), nullable=False),
    sa.Column('completed_rides', sa.String(length=10), nullable=False),
    sa.Column('cancelled_rides', sa.String(length=10), nullable=False),
    sa.Column('total_earnings', sa.Float(), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_branch', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('vehicle_plate_number')
    )
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=True)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_phone_number'), 'drivers', ['phone_number'], unique=True)
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PASSENGER', 'DRIVER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('phone_verification_code', sa.String(length=10), nullable=True),
    sa.Column('verification_code_expires', sa.DateTime(), nullable=True),
    sa.Column('otp_secret', sa.String(length=255), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.String(length=10), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.String(length=10), nullable=False),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR phone_number IS NOT NULL', name='at_least_one_contact_method'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('rides',
    sa.Column('ride_number', sa.String(length=50), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('ride_type', sa.Enum('ECONOMY', 'COMFORT', 'PREMIUM', name='ridetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DRIVER_ARRIVING', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='ridestatus'), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'WALLET', 'UPI', name='paymentmethod'), nullable=False),
    sa.Column('pickup_latitude', sa.Float(), nullable=False),
    sa.Column('pickup_longitude', sa.Float(), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('dropoff_latitude', sa.Float(), nullable=False),
    sa.Column('dropoff_longitude', sa.Float(), nullable=False),
    sa.Column('dropoff_address', sa.String(length=500), nullable=False),
    sa.Column('estimated_fare', sa.Float(), nullable=False),
    sa.Column('actual_fare', sa.Float(), nullable=True),
    sa.Column('discount_applied', sa.Float(), nullable=True),
    sa.Column('final_fare', sa.Float(), nullable=True),
    sa.Column('estimated_distance_km', sa.Float(), nullable=True),
    sa.Column('actual_distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_by', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('is_ride_shared', sa.Boolean(), nullable=True),
    sa.Column('emergency_contact_shared', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    op.create_index(op.f('ix_rides_passenger_id'), 'rides', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_rides_ride_number'), 'rides', ['ride_number'], unique=True)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    op.create_table('locations',
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.Enum('PICKUP', 'DROPOFF', 'WAYPOINT', 'CURRENT', name='locationtype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('place_name', sa.String(length=200), nullable=True),
    sa.Column('floor_number', sa.String(length=20), nullable=True),
    sa.Column('building_name', sa.String(length=200), nullable=True),
    sa.Column('landmark', sa.String(length=500), nullable=True),
    sa.Column('special_instructions', sa.String(length=500), nullable=True),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_location_type'), 'locations', ['location_type'], unique=False)
    op.create_index(op.f('ix_locations_ride_id'), 'locations', ['ride_id'], unique=False)
    op.create_table('payments',
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PROCESSING', name='transactionstatus'), nullable=True),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('distance_charge', sa.Float(), nullable=True),
    sa.Column('time_charge', sa.Float(), nullable=True),
    sa.Column('surge_charge', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('tips', sa.Float(), nullable=True),
    sa.Column('gateway_name', sa.String(length=100), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refund_reason', sa.String(length=500), nullable=True),
    sa.Column('refund_transaction_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_driver_id'), 'payments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_passenger_id'), 'payments', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_payments_ride_id'), 'payments', ['ride_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('ratee_type', sa.String(length=20), nullable=False),
    sa.Column('ratee_id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Float(), nullable=False),
    sa.Column('cleanliness_rating', sa.Float(), nullable=True),
    sa.Column('communication_rating', sa.Float(), nullable=True),
    sa.Column('driving_rating', sa.Float(), nullable=True),
    sa.Column('behavior_rating', sa.Float(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_flagged', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_ratee_id'), 'ratings', ['ratee_id'], unique=False)
    op.create_index(op.f('ix_ratings_rater_id'), 'ratings', ['rater_id'], unique=False)
    op.create_index(op.f('ix_ratings_ride_id'), 'ratings', ['ride_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_ride_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_rater_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_ratee_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_ride_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_passenger_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_driver_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_locations_ride_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_type'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_ride_number'), table_name='rides')
    op.drop_index(op.f('ix_rides_passenger_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_drivers_phone_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
